crowdin/mobile-sdk-ios

.gitignore
azure-pipelines.yml

- Two steps: Build and Test.
- Publishing test results in Azure Pipelines.

Improve CI

---

README.md

New Badges: build, codecov, tests

---

CrowdinSDK/Classes/Features/LoginFeature/Extensions/CrowdinSDK+Login.swift
CrowdinSDK/Classes/Features/LoginFeature/LoginFeature.swift
Example/CrowdinSDK/AppDelegate.swift

Add logout functionality after changiing hash

---

Dangerfile.swift
_dangerfile_imports.swift
azure-pipelines.yml

Add checking for SDK code syntaxis with swiftlint

Add danger-swift plugin

---

README.md

Hi, I'm changing this readme to include the information when it happens to work with `Cocoapods` and `Service Extensions`.
Hope you'll find it useful.

Adding information regarding the App Extensions

---

CrowdinSDK.podspec
CrowdinSDK/Classes/CrowdinAPI/CrowdinAPI.swift
CrowdinSDK/Classes/CrowdinAPI/SupportedLanguagesAPI/LanguagesAPI.swift
Example/CrowdinSDK.xcodeproj/project.pbxproj
Example/Podfile.lock
ObjCExample/Podfile.lock

Small mathod name refactoring.

Add version header to all API calls.

---

CrowdinSDK.podspec
Example/Podfile.lock
ObjCExample/Podfile.lock
Tests/Podfile.lock
Tests/Pods/Local Podspecs/CrowdinSDK.podspec.json
Tests/Pods/Manifest.lock
Tests/Pods/Pods.xcodeproj/project.pbxproj
Tests/Pods/Target Support Files/CrowdinSDK/CrowdinSDK-Info.plist

Update example and test projects

Update podspec version

---

CrowdinSDK.podspec
Example/Podfile.lock

Update starscream version

---

CrowdinSDK/Classes/CrowdinSDK/CrowdinSDK.swift
CrowdinSDK/Classes/Providers/Crowdin/Extensions/CrowdinSDK+CrowdinProvider.swift
Example/CrowdinSDK/AppDelegate.swift
ObjCExample/CrowdinSDK/AppDelegate.m
README.md
Tests/Tests.xcodeproj/project.pbxproj
Tests/UnitTests/AddDownloadHandlersTests.swift
Tests/UnitTests/AddErrorHandlersTests.swift
Tests/UnitTests/CrowdinSDKTests.swift
Tests/UnitTests/CrowdinStringTests.swift
Tests/UnitTests/CrowdinTesterTests.swift
Tests/UnitTests/EnableSDKLocalizationTests.swift
Tests/UnitTests/InfoPlistInitializationTests.swift
Tests/UnitTests/InitializationCompletionHandlerTests.swift
Tests/UnitTests/SDKModeTests.swift

Fix tests.
Add tests for SDK initialization completion handler.
Update README.
Closes #84.

Add sdk initialization completion handler.

---

CrowdinSDK/Classes/CrowdinSDK/Localization/Localization.swift
Example/CrowdinSDK/AppDelegate.swift
Example/CrowdinSDK/R.generated.swift

Fix crash issue in release mode for device running.

---

CrowdinSDK.podspec
Example/Podfile.lock
ObjCExample/Podfile.lock
Tests/Podfile.lock
Tests/Pods/Local Podspecs/CrowdinSDK.podspec.json
Tests/Pods/Manifest.lock
Tests/Pods/Target Support Files/CrowdinSDK/CrowdinSDK-Info.plist

Update podspec version to 1.2.0

---

Example/AppleReminders/SceneDelegate.swift

Added placeholder for each credential of SDK configuration

Adde plceholder for SDK config credentials

---

azure-pipelines.yml

Added check for correct library dependencies

Added pod lint for every build.

---

CrowdinSDK.podspec
Example/Podfile.lock
ObjCExample/Podfile.lock
Tests/Podfile.lock
Tests/Pods/Local Podspecs/CrowdinSDK.podspec.json
Tests/Pods/Manifest.lock
Tests/Pods/Target Support Files/CrowdinSDK/CrowdinSDK-Info.plist

Update pod version to 1.2.3

---

pod_upload.sh

Simple script for uploading new cocoapod version. 
The main goal is to avoid issues with uploading from the wrong branch with local changes.

Add script for cocapopod upload 

---

CrowdinSDK/Classes/CrowdinSDK/CrowdinSDK.swift
CrowdinSDK/Classes/CrowdinSDK/Extensions/UIButton+Swizzle.swift
CrowdinSDK/Classes/CrowdinSDK/Extensions/UILabel+Swizzle.swift
CrowdinSDK/Classes/CrowdinSDK/Localization/Extractor/LocalLocalizationExtractor.swift
CrowdinSDK/Classes/Features/RealtimeUpdateFeature/Extensions/CrowdinSDK+ReatimeUpdates.swift
CrowdinSDK/Classes/Features/ScreenshotFeature/Extensions/CrowdinSDK+Screenshots.swift

Enable realtime preview only when feature is nabled.

Fix issue with cpu usage for realtime updates.

---

Example/AppleReminders/SceneDelegate.swift
Example/Podfile
Example/Podfile.lock
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/LocalizationProvider/FilesDownloader/RUFilesDownloader.swift
Sources/CrowdinSDK/Providers/Crowdin/LocalizationDownloader/CrowdinLocalizationDownloader.swift
Sources/CrowdinSDK/Providers/Crowdin/ManifestManager/ManifestManager.swift
Sources/CrowdinSDK/Providers/Crowdin/MappingDownloader/CrowdinMappingDownloader.swift
Sources/CrowdinSDK/Providers/Crowdin/SupportedLanguages/CrowdinSupportedLanguages.swift

Fix issue with duplicated requests for manifest and supported languages

---

Sources/CrowdinSDK/CrowdinSDK/CrowdinSDK.swift
Sources/CrowdinSDK/CrowdinSDK/Extensions/Bundle/Bundle+Swizzle.swift
Sources/CrowdinSDK/CrowdinSDK/Localization/Provider/LocalLocalizationStorage.swift
Sources/CrowdinSDK/CrowdinSDK/Localization/Provider/LocalizationProvider.swift
Sources/CrowdinSDK/Providers/Crowdin/CrowdinRemoteLocalizationStorage.swift
Sources/CrowdinSDK/Providers/Crowdin/LocalizationDownloader/Operations/CrowdinPluralsDownloadOperation.swift
Sources/Tests/Core/CrowdinRemoteLocalizationStorageTests.swift
Sources/Tests/Core/LocalLocalizationStorageTests.swift
Sources/Tests/Core/LocalizationProviderTests.swift
Sources/Tests/Core/RealLocalizationProviderTests.swift

Localization Provider Tests

---

Example/Podfile.lock
ObjCExample/Podfile.lock
Package.swift
Sources/CrowdinSDK/CrowdinAPI/CrowdinAPI.swift
Sources/CrowdinSDK/CrowdinSDK/CrowdinSDK.swift
Sources/CrowdinSDK/CrowdinSDK/Extensions/UIButton+Swizzle.swift
Sources/CrowdinSDK/CrowdinSDK/Extensions/UILabel+Swizzle.swift
Sources/CrowdinSDK/CrowdinSDK/Extensions/UIView.swift
Sources/CrowdinSDK/CrowdinSDK/Extensions/UIWindow.swift
Sources/CrowdinSDK/CrowdinSDK/Utils/Toast.swift
Tests/Podfile.lock

Fix build errors for watchOS

---

Sources/CrowdinSDK/CrowdinAPI/CrowdinAPI.swift
Sources/Tests/CrowdinAPI/CrowdinAPITests.swift
Sources/Tests/CrowdinAPI/DistributionsAPITests.swift
Sources/Tests/CrowdinAPI/LanguagesAPITests.swift
Sources/Tests/CrowdinAPI/ProjectsAPITests.swift

Solved :Make API calls to the api.crowdin.com instead of crowdin.com #203

changed the api

---

README.md

Fix description of screenshots feature.

---

Package.swift
Sources/CrowdinSDK/Settings/CrowdinLogDetailsVC/CrowdinLogDetailsVC.swift
Sources/CrowdinSDK/Settings/CrowdinLogsVC/CrowdinLogCell/CrowdinLogCell.swift
Sources/CrowdinSDK/Settings/CrowdinLogsVC/CrowdinLogCell/CrowdinLogCellViewModel.swift
Sources/CrowdinSDK/Settings/CrowdinLogsVC/CrowdinLogsVC.swift
Sources/CrowdinSDK/Settings/Extensions/CrowdinSDK+Settings.swift
Sources/CrowdinSDK/Settings/Extensions/CrowdinSDKConfig+Settings.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsItemCell/SettingsItemCell.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsItemCell/SettingsItemView.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsView+Gesture.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsView+UITableView.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsView.swift
Sources/CrowdinSDK/Settings/SettingsWindow/SettingsWindow.swift
azure-pipelines.yml

Skip pod linting for wathOS platform due to issue:
https://github.com/CocoaPods/CocoaPods/issues/11558

Fix issues with. excluding files for iOS and watchOS platforms.

---

Example/AppleReminders/SceneDelegate.swift
Sources/CrowdinSDK/Settings/CrowdinLogDetailsVC/CrowdinLogDetailsVC.swift

Fix issue with log details screen

Fix issue with log details screen

---

CrowdinSDK.podspec
Example/AppleReminders/Controllers/EndRepeatTVC.swift
Example/AppleReminders/Controllers/RepeatTVC.swift
Example/Podfile.lock
Package.resolved
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/SocketAPI/SocketAPI.swift

StarScream enum WebSocketEvent added peerClosed value and new Client type name

Fix WebSocketDelegate

---

Sources/CrowdinSDK/Features/LoginFeature/CrowdinLoginConfig.swift
Sources/CrowdinSDK/Features/LoginFeature/Extensions/CrowdinSDKConfig+Login.swift

Make passing organization name through login config working.

fix: Deprecate method of passing organization name via login config.

---

Sources/CrowdinSDK/Features/LoginFeature/LoginFeature.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsView+UITableView.swift
Sources/CrowdinSDK/Settings/SettingsView/SettingsView.swift

fix: Add clearing login credentials by removing safari web history

---

.github/workflows/build.yml
Sources/CrowdinSDK/CrowdinSDK/CrowdinSDK.swift
Sources/CrowdinSDK/CrowdinSDK/Extensions/Label+Swizzle/Label+Swizzle.swift
Sources/CrowdinSDK/CrowdinSDK/PlatformsSupport/CrowdinSDK+PlatformsSupport.swift
Sources/CrowdinSDK/Features/LoginFeature/BrowserLoginFeature.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/Extensions/Label+RealtimeUpdates.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/RealtimeUpdateFeature.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/Refreshable.swift
Sources/CrowdinSDK/Features/ScreenshotFeature/Extensions/CrowdinSDK+Screenshots.swift
Sources/CrowdinSDK/Features/ScreenshotFeature/ScreenshotFeature.swift
Sources/CrowdinSDK/Features/ScreenshotFeature/ScreenshotInformationCollector.swift
Sources/CrowdinSDK/Features/ScreenshotFeature/ScreenshotProcessor.swift
Sources/CrowdinSDK/Features/ScreenshotFeature/ScreenshotUploader.swift
Sources/CrowdinSDK/Features/XCTestScreenshotFeature/ScreenshotFeature+XCTest.swift

Fix build errors for macOS and watchOS platforms.

fix: SPM build workflow

---

Sources/CrowdinSDK/CrowdinFileSystem/File.swift
Sources/CrowdinSDK/CrowdinSDK/Localization/Provider/LocalizationProvider.swift
Sources/CrowdinSDK/Providers/Crowdin/LocalizationDownloader/CrowdinLocalizationDownloader.swift
Sources/CrowdinSDK/Providers/Crowdin/LocalizationDownloader/ETagStorage/FileEtagStorage.swift
Sources/CrowdinSDK/Providers/Crowdin/LocalizationDownloader/Operations/CrowdinXcstringsDownloadOperation.swift
Sources/CrowdinSDK/Providers/Crowdin/ManifestManager/ManifestManager.swift

- Fix issue with detecting language to download xcstrings files.
- Fix issue with saving e-tags for xcstrings file:
1. Make e-tag storage atomic. 
2. Read file content before adding new e-tag. 
3. Add serial queue for writing operations.

fix: Issue with detecting language to download xcstrings files

---

Sources/CrowdinSDK/Providers/Crowdin/LocalizationDownloader/CrowdinLocalizationDownloader.swift

Fix concurrency issue in CrowdinLocalizationDownloader that was causing crashes when multiple threads attempted to modify shared dictionaries simultaneously. Implemented NSLock to ensure thread-safe access to shared resources (strings, plurals, and errors collections).
Closes #318

fix: Add thread safety to CrowdinLocalizationDownloader

---

Sources/CrowdinSDK/CrowdinAPI/WebsocketAPI/WebsocketAPI.swift
Sources/CrowdinSDK/CrowdinAPI/WebsocketAPI/WebsocketTicketCache.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/CrowdinSocketManager/CrowdinSocketManager.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/RealtimeUpdateFeature.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/SocketAPI/Models/ActionRequest.swift
Sources/CrowdinSDK/Features/RealtimeUpdateFeature/SocketAPI/SocketAPI.swift

Add WebsocketAPI to get real time updates ticket for strings change subscriptions. Add tickets caching to reuse it for controls text change subscription. Add ticket ttl 4 minutes check.

feat: Improve security for real time updates feature
